# mysql数据库的相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_sql?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        max-active: 20
        initial-size: 1
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
# Redis 数据库的相关配置
  redis:
    #redis数据库索引(默认为0)
    database : 0
    #redis服务器地址
    host: 127.0.0.1
    #redis服务器连接端口
    port: 6379
    #redis连接密码
    password:
    #redis连接池设置
    pool:
      #最大空闲连接
      max-idle : 100
      #最小空闲连接
      min-idle : 1
      #最大连接数(负数表示没有限制)
      max-active : 1000
      #最大阻塞等待时间(负数表示没有限制)
      max-wait : -1
      #连接超时时间(毫秒)
    timeout : 5000
# mybatis文件的扫描
mybatis:
  mapper-locations: classpath:mappers/*.xml

# mybatis执行SQL语句的配置
logging:
  level:
    com.example.springboot.dao: info

# mybatis plus 指定文件的扫描路径 config-location: classpath:mappers/*.xml
#mybatis-plus:
  #mapper-locations: classpath:mappers/*.xml

# springboot 中去掉不必要的日志打印信息配置
logging.level.org.springframework.boot.autoconfigure: ERROR

# 配置服务器的地址
server:
  port: 8090
  servlet:
    context-path: /



